name: KaiPro Auto-Evolve

on:
  schedule:
    - cron: "0 3 * * *"  # daily 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  kaipro:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout control repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run KaiPro trainer
        env:
          KAI_PAT: ${{ secrets.KAI_PAT }}
          DIRECT_PUSH: "false"   # change to "true" in repo secrets if you trust it
        run: |
          python kai_pro_trainer.py

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kaipro-logs
          path: |
            logs/
            artifacts/
