name: Kai Multi-Repo Maintainer

on:
  schedule:
    - cron: "0 2 * * *"   # daily at 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  maintain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Control Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run Kai Maintainer
        env:
          KAI_PAT: ${{ secrets.KAI_PAT }}
          OWNER: Neo77x
          DIRECT_PUSH: "false"   # set to "true" to push directly instead of PR
        run: |
          python kai_maintainer.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kai-maintainer-logs
          path: |
            maintainer.log
