name: Kai Eternal Loop

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  evolve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-api-python-client PyGithub

      - name: Run Kai Evolution
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: |
          python ultra_kai_omniscient.py

      - name: Commit and Push Changes
        run: |
          git config user.name "KaiBot"
          git config user.email "kai@bot.ai"
          git add -A
          git commit -m "Kai auto-evolved [skip ci]" || echo "No changes"
          git push origin master --force
